version: '3.7'

services:
  companies_prod_web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    #command: "npm run start"
    image: companies-prod-web:1.0
    restart: always
    container_name: companies_prod_web
    networks:
      companies_prod_net:
        ipv4_address: 172.31.0.6


networks:
  companies_prod_net:
    name: companies_prod_net
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24

