FROM node:14.13.1-alpine3.12

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY web/package*.json ./
RUN npm install

# Copying source files
COPY web/ .

# Building app
RUN npm run build

EXPOSE 3000

# Running the app
CMD [ "npm", "start" ]
